/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  CreateTechnologyDto,
  TechnologiesControllerFindAllParams,
  TechnologyDto,
  TechnologyListResponseDto,
  UpdateTechnologyDto
} from '.././';


/**
 * @summary Create a new technology
 */
export const getTechnologiesControllerCreateUrl = () => {


  

  return `/api/technologies`
}

export const technologiesControllerCreate = async (createTechnologyDto: CreateTechnologyDto, options?: RequestInit): Promise<TechnologyDto> => {
  
  const res = await fetch(getTechnologiesControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTechnologyDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: TechnologyDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary List all technologies
 */
export const getTechnologiesControllerFindAllUrl = (params: TechnologiesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/technologies?${stringifiedParams}` : `/api/technologies`
}

export const technologiesControllerFindAll = async (params: TechnologiesControllerFindAllParams, options?: RequestInit): Promise<TechnologyListResponseDto> => {
  
  const res = await fetch(getTechnologiesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: TechnologyListResponseDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Get a technology by ID
 */
export const getTechnologiesControllerFindOneUrl = (id: string,) => {


  

  return `/api/technologies/${id}`
}

export const technologiesControllerFindOne = async (id: string, options?: RequestInit): Promise<TechnologyDto> => {
  
  const res = await fetch(getTechnologiesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: TechnologyDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Update a technology
 */
export const getTechnologiesControllerUpdateUrl = (id: string,) => {


  

  return `/api/technologies/${id}`
}

export const technologiesControllerUpdate = async (id: string,
    updateTechnologyDto: UpdateTechnologyDto, options?: RequestInit): Promise<TechnologyDto> => {
  
  const res = await fetch(getTechnologiesControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTechnologyDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: TechnologyDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Delete a technology
 */
export const getTechnologiesControllerRemoveUrl = (id: string,) => {


  

  return `/api/technologies/${id}`
}

export const technologiesControllerRemove = async (id: string, options?: RequestInit): Promise<TechnologyDto> => {
  
  const res = await fetch(getTechnologiesControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: TechnologyDto = body ? JSON.parse(body) : {}
  return data
}


