/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/users - Get all users
         *
         *     Returns array of users (without passwords)
         */
        get: operations["UsersController_findAll"];
        put?: never;
        /**
         * POST /api/users - Create a new user
         *
         *     Request body is automatically validated against CreateUserDto
         *     If validation fails, NestJS returns 400 Bad Request
         */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/users/:id - Get a single user by ID
         *
         *     @Param('id') extracts the :id from the URL
         */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /**
         * DELETE /api/users/:id - Delete a user
         *
         *     Returns the deleted user data
         */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /**
         * PATCH /api/users/:id - Update a user
         *
         *     PATCH = partial update (only send fields you want to change)
         *     PUT = full replacement (must send all fields)
         *
         *     We use PATCH because it's more practical for updates
         */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user profile */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects with optional filters */
        get: operations["ProjectsController_findAll"];
        put?: never;
        /** Create a new project */
        post: operations["ProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get featured projects for homepage */
        get: operations["ProjectsController_findFeatured"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{idOrSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project by ID or slug */
        get: operations["ProjectsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["ProjectsController_remove"];
        options?: never;
        head?: never;
        /** Update a project */
        patch: operations["ProjectsController_update"];
        trace?: never;
    };
    "/api/technologies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all technologies */
        get: operations["TechnologiesController_findAll"];
        put?: never;
        /** Create a new technology */
        post: operations["TechnologiesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technologies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a technology by ID */
        get: operations["TechnologiesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a technology */
        delete: operations["TechnologiesController_remove"];
        options?: never;
        head?: never;
        /** Update a technology */
        patch: operations["TechnologiesController_update"];
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all skills */
        get: operations["SkillsController_findAll"];
        put?: never;
        /** Create a new skill */
        post: operations["SkillsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/grouped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get skills grouped by category */
        get: operations["SkillsController_findGrouped"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a skill by ID */
        get: operations["SkillsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a skill */
        delete: operations["SkillsController_remove"];
        options?: never;
        head?: never;
        /** Update a skill */
        patch: operations["SkillsController_update"];
        trace?: never;
    };
    "/api/experience": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all work experience */
        get: operations["ExperienceController_findAll"];
        put?: never;
        /** Create a new experience entry */
        post: operations["ExperienceController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experience/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an experience entry by ID */
        get: operations["ExperienceController_findOne"];
        put?: never;
        post?: never;
        /** Delete an experience entry */
        delete: operations["ExperienceController_remove"];
        options?: never;
        head?: never;
        /** Update an experience entry */
        patch: operations["ExperienceController_update"];
        trace?: never;
    };
    "/api/media/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an image file */
        post: operations["MediaController_uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an uploaded file */
        delete: operations["MediaController_deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /**
             * Format: email
             * @description User's email address - used for login
             * @example ayyaz@example.com
             */
            email: string;
            /**
             * @description User's password - will be hashed before storage
             * @example securePassword123
             */
            password: string;
            /**
             * @description User's display name (optional)
             * @example Ayyaz Zafar
             */
            name?: string;
            /**
             * @description User's role - defaults to ADMIN in database if not provided
             * @example ADMIN
             * @enum {string}
             */
            role?: "ADMIN" | "VIEWER";
        };
        UpdateUserDto: Record<string, never>;
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        CreateProjectImageDto: {
            /** Format: uri */
            url: string;
            alt?: string;
            order: number;
        };
        CreateProjectDto: {
            /**
             * @description URL-friendly identifier for the project
             * @example spendnest
             */
            slug: string;
            /**
             * @description Display title
             * @example SpendNest - Expense Tracker
             */
            title: string;
            /**
             * @description Short description (for cards/listings)
             * @example Personal expense tracking application
             */
            description?: string;
            /**
             * @description Full description with details (optional)
             * @example SpendNest is a comprehensive expense tracking app...
             */
            longDescription?: string;
            /**
             * @description Project status
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "COMPLETED" | "PAUSED" | "ARCHIVED";
            /**
             * @description Project type/category
             * @example PRODUCT
             * @enum {string}
             */
            type: "PRODUCT" | "CLIENT" | "EXPERIMENT" | "LEARNING";
            /**
             * Format: uri
             * @description Live project URL (optional)
             * @example https://spendnest.app
             */
            url?: string;
            /**
             * Format: uri
             * @description GitHub repository URL (optional)
             * @example https://github.com/ayyaz/spendnest
             */
            github?: string;
            /**
             * @description Featured on homepage?
             * @example true
             */
            featured?: boolean;
            /**
             * @description Display order (lower = first)
             * @example 1
             */
            order?: number;
            /**
             * @description When project was started
             * @example 2024-01-15
             */
            startedAt?: string;
            /**
             * @description When project was completed (if applicable)
             * @example 2024-06-30
             */
            completedAt?: string;
            /**
             * @description Array of technology IDs to associate with this project
             * @example [
             *       "tech-id-1",
             *       "tech-id-2"
             *     ]
             */
            technologyIds?: string[];
            /** @description Array of images for the project */
            images?: components["schemas"]["CreateProjectImageDto"][];
        };
        ProjectImageDto: {
            id?: string;
            /** Format: uri */
            url: string;
            alt?: string;
            order: number;
        };
        UpdateProjectDto: {
            /**
             * @description Array of images for the project
             *     This will replace all existing images with the new set
             */
            images?: components["schemas"]["ProjectImageDto"][];
        };
        CreateTechnologyDto: {
            /**
             * @description Technology name (unique)
             * @example Next.js
             */
            name: string;
            /**
             * @description Icon identifier or URL (optional)
             *     Could be a simple icon name or full URL
             * @example "nextjs" or "https://cdn.example.com/icons/nextjs.svg"
             */
            icon?: string;
        };
        UpdateTechnologyDto: Record<string, never>;
        CreateSkillDto: {
            /**
             * @description Skill name
             * @example React
             */
            name: string;
            /**
             * @description Skill category for grouping
             * @example FRONTEND
             * @enum {string}
             */
            category: "FRONTEND" | "BACKEND" | "DATABASE" | "DEVOPS" | "TOOLS" | "AI";
            /**
             * @description Proficiency level (0-100)
             * @default 80
             * @example 90
             */
            level: number;
            /**
             * @description Display order (lower = first)
             * @default 0
             * @example 1
             */
            order: number;
        };
        UpdateSkillDto: {
            /**
             * @description Skill name
             * @example React
             */
            name?: string;
            /**
             * @description Skill category for grouping
             * @example FRONTEND
             * @enum {string}
             */
            category?: "FRONTEND" | "BACKEND" | "DATABASE" | "DEVOPS" | "TOOLS" | "AI";
            /**
             * @description Proficiency level (0-100)
             * @default 80
             * @example 90
             */
            level: number;
            /**
             * @description Display order (lower = first)
             * @default 0
             * @example 1
             */
            order: number;
        };
        CreateExperienceDto: {
            /**
             * @description Company name
             * @example Tech Corp
             */
            company: string;
            /**
             * @description Job role/title
             * @example Senior Full Stack Developer
             */
            role: string;
            /**
             * @description Role description (optional, can include achievements)
             * @example Led development of microservices architecture...
             */
            description?: string;
            /**
             * @description Start date
             * @example 2020-01-15
             */
            startDate: string;
            /**
             * @description End date (null if current position)
             * @example 2023-06-30
             */
            endDate?: string;
            /**
             * @description Is this the current position?
             * @default false
             * @example true
             */
            current: boolean;
            /**
             * @description Display order (lower = first, typically most recent)
             * @default 0
             * @example 0
             */
            order: number;
        };
        UpdateExperienceDto: {
            /**
             * @description Company name
             * @example Tech Corp
             */
            company?: string;
            /**
             * @description Job role/title
             * @example Senior Full Stack Developer
             */
            role?: string;
            /**
             * @description Role description (optional, can include achievements)
             * @example Led development of microservices architecture...
             */
            description?: string;
            /**
             * @description Start date
             * @example 2020-01-15
             */
            startDate?: string;
            /**
             * @description End date (null if current position)
             * @example 2023-06-30
             */
            endDate?: string;
            /**
             * @description Is this the current position?
             * @default false
             * @example true
             */
            current: boolean;
            /**
             * @description Display order (lower = first, typically most recent)
             * @default 0
             * @example 0
             */
            order: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProjectsController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by project status */
                status?: "ACTIVE" | "COMPLETED" | "PAUSED" | "ARCHIVED";
                /** @description Filter by project type */
                type?: "PRODUCT" | "CLIENT" | "EXPERIMENT" | "LEARNING";
                /**
                 * @description Filter featured projects only
                 *
                 *     WORKAROUND: Query params come as strings. With enableImplicitConversion,
                 *     the string "false" becomes true (Boolean("false") === true in JS).
                 *     Solution: Keep as optional string, convert in the service layer.
                 *
                 *     Valid values: "true", "false", "1", "0"
                 */
                featured?: "true" | "false" | "1" | "0";
                /** @description Number of records to skip (for pagination) */
                skip?: number;
                /** @description Number of records to return (limit) */
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProjectsController_findFeatured: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    ProjectsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOrSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProjectsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    TechnologiesController_findAll: {
        parameters: {
            query: {
                skip: string;
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TechnologiesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTechnologyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TechnologiesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TechnologiesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TechnologiesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTechnologyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SkillsController_findAll: {
        parameters: {
            query?: {
                category?: "FRONTEND" | "BACKEND" | "DATABASE" | "DEVOPS" | "TOOLS" | "AI";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SkillsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSkillDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SkillsController_findGrouped: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SkillsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SkillsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SkillsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSkillDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExperienceController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExperienceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExperienceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExperienceController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExperienceController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExperienceController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExperienceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
