/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  MediaControllerUploadFileBody
} from '.././';


/**
 * @summary Upload an image file
 */
export type mediaControllerUploadFileResponse201 = {
  data: void
  status: 201
}
    
export type mediaControllerUploadFileResponseSuccess = (mediaControllerUploadFileResponse201) & {
  headers: Headers;
};
;

export type mediaControllerUploadFileResponse = (mediaControllerUploadFileResponseSuccess)

export const getMediaControllerUploadFileUrl = () => {


  

  return `/api/media/upload`
}

export const mediaControllerUploadFile = async (mediaControllerUploadFileBody: MediaControllerUploadFileBody, options?: RequestInit): Promise<mediaControllerUploadFileResponse> => {
    const formData = new FormData();
if(mediaControllerUploadFileBody.file !== undefined) {
 formData.append(`file`, mediaControllerUploadFileBody.file)
 }

  const res = await fetch(getMediaControllerUploadFileUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: mediaControllerUploadFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as mediaControllerUploadFileResponse
}


/**
 * @summary Delete an uploaded file
 */
export type mediaControllerDeleteFileResponse200 = {
  data: void
  status: 200
}
    
export type mediaControllerDeleteFileResponseSuccess = (mediaControllerDeleteFileResponse200) & {
  headers: Headers;
};
;

export type mediaControllerDeleteFileResponse = (mediaControllerDeleteFileResponseSuccess)

export const getMediaControllerDeleteFileUrl = (key: string,) => {


  

  return `/api/media/${key}`
}

export const mediaControllerDeleteFile = async (key: string, options?: RequestInit): Promise<mediaControllerDeleteFileResponse> => {
  
  const res = await fetch(getMediaControllerDeleteFileUrl(key),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: mediaControllerDeleteFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as mediaControllerDeleteFileResponse
}


