/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  CreateUserDto,
  UpdateUserDto,
  UsersControllerCreate201,
  UsersControllerFindAll200Item,
  UsersControllerFindOne200,
  UsersControllerRemove200,
  UsersControllerUpdate200
} from '.././';


/**
 * @summary POST /api/users - Create a new user

Request body is automatically validated against CreateUserDto
If validation fails, NestJS returns 400 Bad Request
 */
export type usersControllerCreateResponse201 = {
  data: UsersControllerCreate201
  status: 201
}
    
export type usersControllerCreateResponseSuccess = (usersControllerCreateResponse201) & {
  headers: Headers;
};
;

export type usersControllerCreateResponse = (usersControllerCreateResponseSuccess)

export const getUsersControllerCreateUrl = () => {


  

  return `/api/users`
}

export const usersControllerCreate = async (createUserDto: CreateUserDto, options?: RequestInit): Promise<usersControllerCreateResponse> => {
  
  const res = await fetch(getUsersControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerCreateResponse
}


/**
 * @summary GET /api/users - Get all users

Returns array of users (without passwords)
 */
export type usersControllerFindAllResponse200 = {
  data: UsersControllerFindAll200Item[]
  status: 200
}
    
export type usersControllerFindAllResponseSuccess = (usersControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type usersControllerFindAllResponse = (usersControllerFindAllResponseSuccess)

export const getUsersControllerFindAllUrl = () => {


  

  return `/api/users`
}

export const usersControllerFindAll = async ( options?: RequestInit): Promise<usersControllerFindAllResponse> => {
  
  const res = await fetch(getUsersControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerFindAllResponse
}


/**
 * @summary GET /api/users/:id - Get a single user by ID

@Param('id') extracts the :id from the URL
 */
export type usersControllerFindOneResponse200 = {
  data: UsersControllerFindOne200
  status: 200
}
    
export type usersControllerFindOneResponseSuccess = (usersControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type usersControllerFindOneResponse = (usersControllerFindOneResponseSuccess)

export const getUsersControllerFindOneUrl = (id: string,) => {


  

  return `/api/users/${id}`
}

export const usersControllerFindOne = async (id: string, options?: RequestInit): Promise<usersControllerFindOneResponse> => {
  
  const res = await fetch(getUsersControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerFindOneResponse
}


/**
 * @summary PATCH /api/users/:id - Update a user

PATCH = partial update (only send fields you want to change)
PUT = full replacement (must send all fields)

We use PATCH because it's more practical for updates
 */
export type usersControllerUpdateResponse200 = {
  data: UsersControllerUpdate200
  status: 200
}
    
export type usersControllerUpdateResponseSuccess = (usersControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type usersControllerUpdateResponse = (usersControllerUpdateResponseSuccess)

export const getUsersControllerUpdateUrl = (id: string,) => {


  

  return `/api/users/${id}`
}

export const usersControllerUpdate = async (id: string,
    updateUserDto: UpdateUserDto, options?: RequestInit): Promise<usersControllerUpdateResponse> => {
  
  const res = await fetch(getUsersControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerUpdateResponse
}


/**
 * @summary DELETE /api/users/:id - Delete a user

Returns the deleted user data
 */
export type usersControllerRemoveResponse200 = {
  data: UsersControllerRemove200
  status: 200
}
    
export type usersControllerRemoveResponseSuccess = (usersControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type usersControllerRemoveResponse = (usersControllerRemoveResponseSuccess)

export const getUsersControllerRemoveUrl = (id: string,) => {


  

  return `/api/users/${id}`
}

export const usersControllerRemove = async (id: string, options?: RequestInit): Promise<usersControllerRemoveResponse> => {
  
  const res = await fetch(getUsersControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerRemoveResponse
}


