/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type { CreateSkillDtoCategory } from './createSkillDtoCategory';

export interface CreateSkillDto {
  /**
   * Skill name
   * @minLength 1
   */
  name: string;
  /** Skill category for grouping */
  category: CreateSkillDtoCategory;
  /**
   * Proficiency level (0-100)
   * @minimum 0
   * @maximum 100
   */
  level?: number;
  /**
   * Display order (lower = first)
   * @minimum 0
   */
  order?: number;
}
