/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type { ProjectsControllerFindAllStatus } from './projectsControllerFindAllStatus';
import type { ProjectsControllerFindAllType } from './projectsControllerFindAllType';
import type { ProjectsControllerFindAllFeatured } from './projectsControllerFindAllFeatured';

export type ProjectsControllerFindAllParams = {
/**
 * Filter by project status
 */
status?: ProjectsControllerFindAllStatus;
/**
 * Filter by project type
 */
type?: ProjectsControllerFindAllType;
/**
 * Filter featured projects only

WORKAROUND: Query params come as strings. With enableImplicitConversion,
the string "false" becomes true (Boolean("false") === true in JS).
Solution: Keep as optional string, convert in the service layer.

Valid values: "true", "false", "1", "0"
 */
featured?: ProjectsControllerFindAllFeatured;
/**
 * Number of records to skip (for pagination)
 * @minimum 0
 */
skip?: number;
/**
 * Number of records to return (limit)
 * @minimum 1
 * @maximum 100
 */
take?: number;
};
