/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */

/**
 * Skill category for grouping
 */
export type UpdateSkillDtoCategory = typeof UpdateSkillDtoCategory[keyof typeof UpdateSkillDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSkillDtoCategory = {
  FRONTEND: 'FRONTEND',
  BACKEND: 'BACKEND',
  DATABASE: 'DATABASE',
  DEVOPS: 'DEVOPS',
  TOOLS: 'TOOLS',
  AI: 'AI',
} as const;
