/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */

/**
 * Project type/category
 */
export type CreateProjectDtoType = typeof CreateProjectDtoType[keyof typeof CreateProjectDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProjectDtoType = {
  PRODUCT: 'PRODUCT',
  CLIENT: 'CLIENT',
  EXPERIMENT: 'EXPERIMENT',
  LEARNING: 'LEARNING',
} as const;
