/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type { ProjectDtoStatus } from './projectDtoStatus';
import type { ProjectDtoType } from './projectDtoType';
import type { ProjectTechnologyDto } from './projectTechnologyDto';
import type { ProjectImageDto } from './projectImageDto';

export interface ProjectDto {
  /** Project ID */
  id: string;
  /** URL-friendly slug */
  slug: string;
  /** Display title */
  title: string;
  /**
   * Short description
   * @nullable
   */
  description: string | null;
  /**
   * Full description
   * @nullable
   */
  longDescription: string | null;
  /** Project status */
  status: ProjectDtoStatus;
  /** Project type */
  type: ProjectDtoType;
  /**
   * Live project URL
   * @nullable
   */
  url: string | null;
  /**
   * GitHub repository URL
   * @nullable
   */
  github: string | null;
  /** Featured on homepage */
  featured: boolean;
  /** Display order */
  order: number;
  /**
   * When project was started
   * @nullable
   */
  startedAt: string | null;
  /**
   * When project was completed
   * @nullable
   */
  completedAt: string | null;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
  /** Associated technologies */
  technologies?: ProjectTechnologyDto[];
  /** Project images */
  images?: ProjectImageDto[];
}
