/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoRole } from './updateUserDtoRole';

export interface UpdateUserDto {
  /** User's email address - used for login */
  email?: string;
  /**
   * User's password - will be hashed before storage
   * @minLength 8
   */
  password?: string;
  /** User's display name (optional) */
  name?: string;
  /** User's role - defaults to ADMIN in database if not provided */
  role?: UpdateUserDtoRole;
}
