/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type { ProjectImageDto } from './projectImageDto';
import type { UpdateProjectDtoStatus } from './updateProjectDtoStatus';
import type { UpdateProjectDtoType } from './updateProjectDtoType';

export interface UpdateProjectDto {
  /** Array of images for the project
This will replace all existing images with the new set */
  images?: ProjectImageDto[];
  /**
   * URL-friendly identifier for the project
   * @minLength 2
   * @pattern /^[a-z0-9-]+$/
   */
  slug?: string;
  /**
   * Display title
   * @minLength 2
   */
  title?: string;
  /**
   * Short description (for cards/listings)
   * @minLength 10
   */
  description?: string;
  /** Full description with details (optional) */
  longDescription?: string;
  /** Project status */
  status?: UpdateProjectDtoStatus;
  /** Project type/category */
  type?: UpdateProjectDtoType;
  /** Live project URL (optional) */
  url?: string;
  /** GitHub repository URL (optional) */
  github?: string;
  /** Featured on homepage? */
  featured?: boolean;
  /**
   * Display order (lower = first)
   * @minimum 0
   */
  order?: number;
  /** When project was started */
  startedAt?: string;
  /** When project was completed (if applicable) */
  completedAt?: string;
  /** Array of technology IDs to associate with this project */
  technologyIds?: string[];
}
