/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */

export interface UpdateExperienceDto {
  /**
   * Company name
   * @minLength 1
   */
  company?: string;
  /**
   * Job role/title
   * @minLength 1
   */
  role?: string;
  /** Role description (optional, can include achievements) */
  description?: string;
  /** Start date */
  startDate?: string;
  /** End date (null if current position) */
  endDate?: string;
  /** Is this the current position? */
  current?: boolean;
  /**
   * Display order (lower = first, typically most recent)
   * @minimum 0
   */
  order?: number;
}
