/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  LoginDto,
  LoginResponseDto,
  UserResponseDto
} from '.././';


/**
 * @summary Login with email and password
 */
export const getAuthControllerLoginUrl = () => {


  

  return `/api/auth/login`
}

export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<LoginResponseDto> => {
  
  const res = await fetch(getAuthControllerLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: LoginResponseDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Get current authenticated user profile
 */
export const getAuthControllerGetMeUrl = () => {


  

  return `/api/auth/me`
}

export const authControllerGetMe = async ( options?: RequestInit): Promise<UserResponseDto> => {
  
  const res = await fetch(getAuthControllerGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: UserResponseDto = body ? JSON.parse(body) : {}
  return data
}


