/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  CreateProjectDto,
  ProjectDto,
  ProjectListResponseDto,
  ProjectsControllerFindAllParams,
  UpdateProjectDto
} from '.././';


/**
 * @summary Create a new project
 */
export type projectsControllerCreateResponse201 = {
  data: ProjectDto
  status: 201
}
    
export type projectsControllerCreateResponseSuccess = (projectsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type projectsControllerCreateResponse = (projectsControllerCreateResponseSuccess)

export const getProjectsControllerCreateUrl = () => {


  

  return `/api/projects`
}

export const projectsControllerCreate = async (createProjectDto: CreateProjectDto, options?: RequestInit): Promise<projectsControllerCreateResponse> => {
  
  const res = await fetch(getProjectsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerCreateResponse
}


/**
 * @summary List all projects with optional filters
 */
export type projectsControllerFindAllResponse200 = {
  data: ProjectListResponseDto
  status: 200
}
    
export type projectsControllerFindAllResponseSuccess = (projectsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type projectsControllerFindAllResponse = (projectsControllerFindAllResponseSuccess)

export const getProjectsControllerFindAllUrl = (params?: ProjectsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/projects?${stringifiedParams}` : `/api/projects`
}

export const projectsControllerFindAll = async (params?: ProjectsControllerFindAllParams, options?: RequestInit): Promise<projectsControllerFindAllResponse> => {
  
  const res = await fetch(getProjectsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerFindAllResponse
}


/**
 * @summary Get featured projects for homepage
 */
export type projectsControllerFindFeaturedResponse200 = {
  data: ProjectDto[]
  status: 200
}
    
export type projectsControllerFindFeaturedResponseSuccess = (projectsControllerFindFeaturedResponse200) & {
  headers: Headers;
};
;

export type projectsControllerFindFeaturedResponse = (projectsControllerFindFeaturedResponseSuccess)

export const getProjectsControllerFindFeaturedUrl = () => {


  

  return `/api/projects/featured`
}

export const projectsControllerFindFeatured = async ( options?: RequestInit): Promise<projectsControllerFindFeaturedResponse> => {
  
  const res = await fetch(getProjectsControllerFindFeaturedUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerFindFeaturedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerFindFeaturedResponse
}


/**
 * @summary Get a project by ID or slug
 */
export type projectsControllerFindOneResponse200 = {
  data: ProjectDto
  status: 200
}
    
export type projectsControllerFindOneResponseSuccess = (projectsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type projectsControllerFindOneResponse = (projectsControllerFindOneResponseSuccess)

export const getProjectsControllerFindOneUrl = (idOrSlug: string,) => {


  

  return `/api/projects/${idOrSlug}`
}

export const projectsControllerFindOne = async (idOrSlug: string, options?: RequestInit): Promise<projectsControllerFindOneResponse> => {
  
  const res = await fetch(getProjectsControllerFindOneUrl(idOrSlug),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerFindOneResponse
}


/**
 * @summary Update a project
 */
export type projectsControllerUpdateResponse200 = {
  data: ProjectDto
  status: 200
}
    
export type projectsControllerUpdateResponseSuccess = (projectsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type projectsControllerUpdateResponse = (projectsControllerUpdateResponseSuccess)

export const getProjectsControllerUpdateUrl = (id: string,) => {


  

  return `/api/projects/${id}`
}

export const projectsControllerUpdate = async (id: string,
    updateProjectDto: UpdateProjectDto, options?: RequestInit): Promise<projectsControllerUpdateResponse> => {
  
  const res = await fetch(getProjectsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProjectDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerUpdateResponse
}


/**
 * @summary Delete a project
 */
export type projectsControllerRemoveResponse200 = {
  data: ProjectDto
  status: 200
}
    
export type projectsControllerRemoveResponseSuccess = (projectsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type projectsControllerRemoveResponse = (projectsControllerRemoveResponseSuccess)

export const getProjectsControllerRemoveUrl = (id: string,) => {


  

  return `/api/projects/${id}`
}

export const projectsControllerRemove = async (id: string, options?: RequestInit): Promise<projectsControllerRemoveResponse> => {
  
  const res = await fetch(getProjectsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerRemoveResponse
}


