/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  CreateProjectDto,
  ProjectDto,
  ProjectListResponseDto,
  ProjectsControllerFindAllParams,
  UpdateProjectDto
} from '.././';


/**
 * @summary Create a new project
 */
export const getProjectsControllerCreateUrl = () => {


  

  return `/api/projects`
}

export const projectsControllerCreate = async (createProjectDto: CreateProjectDto, options?: RequestInit): Promise<ProjectDto> => {
  
  const res = await fetch(getProjectsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ProjectDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary List all projects with optional filters
 */
export const getProjectsControllerFindAllUrl = (params?: ProjectsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/projects?${stringifiedParams}` : `/api/projects`
}

export const projectsControllerFindAll = async (params?: ProjectsControllerFindAllParams, options?: RequestInit): Promise<ProjectListResponseDto> => {
  
  const res = await fetch(getProjectsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ProjectListResponseDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Get featured projects for homepage
 */
export const getProjectsControllerFindFeaturedUrl = () => {


  

  return `/api/projects/featured`
}

export const projectsControllerFindFeatured = async ( options?: RequestInit): Promise<ProjectDto[]> => {
  
  const res = await fetch(getProjectsControllerFindFeaturedUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ProjectDto[] = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Get a project by ID or slug
 */
export const getProjectsControllerFindOneUrl = (idOrSlug: string,) => {


  

  return `/api/projects/${idOrSlug}`
}

export const projectsControllerFindOne = async (idOrSlug: string, options?: RequestInit): Promise<ProjectDto> => {
  
  const res = await fetch(getProjectsControllerFindOneUrl(idOrSlug),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ProjectDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Update a project
 */
export const getProjectsControllerUpdateUrl = (id: string,) => {


  

  return `/api/projects/${id}`
}

export const projectsControllerUpdate = async (id: string,
    updateProjectDto: UpdateProjectDto, options?: RequestInit): Promise<ProjectDto> => {
  
  const res = await fetch(getProjectsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProjectDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ProjectDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Delete a project
 */
export const getProjectsControllerRemoveUrl = (id: string,) => {


  

  return `/api/projects/${id}`
}

export const projectsControllerRemove = async (id: string, options?: RequestInit): Promise<ProjectDto> => {
  
  const res = await fetch(getProjectsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ProjectDto = body ? JSON.parse(body) : {}
  return data
}


