/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  CreateSkillDto,
  SkillDto,
  SkillsControllerFindAllParams,
  SkillsControllerFindGrouped200,
  UpdateSkillDto
} from '.././';


/**
 * @summary Create a new skill
 */
export type skillsControllerCreateResponse201 = {
  data: SkillDto
  status: 201
}
    
export type skillsControllerCreateResponseSuccess = (skillsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type skillsControllerCreateResponse = (skillsControllerCreateResponseSuccess)

export const getSkillsControllerCreateUrl = () => {


  

  return `/api/skills`
}

export const skillsControllerCreate = async (createSkillDto: CreateSkillDto, options?: RequestInit): Promise<skillsControllerCreateResponse> => {
  
  const res = await fetch(getSkillsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSkillDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: skillsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as skillsControllerCreateResponse
}


/**
 * @summary List all skills
 */
export type skillsControllerFindAllResponse200 = {
  data: SkillDto[]
  status: 200
}
    
export type skillsControllerFindAllResponseSuccess = (skillsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type skillsControllerFindAllResponse = (skillsControllerFindAllResponseSuccess)

export const getSkillsControllerFindAllUrl = (params?: SkillsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/skills?${stringifiedParams}` : `/api/skills`
}

export const skillsControllerFindAll = async (params?: SkillsControllerFindAllParams, options?: RequestInit): Promise<skillsControllerFindAllResponse> => {
  
  const res = await fetch(getSkillsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: skillsControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as skillsControllerFindAllResponse
}


/**
 * @summary Get skills grouped by category
 */
export type skillsControllerFindGroupedResponse200 = {
  data: SkillsControllerFindGrouped200
  status: 200
}
    
export type skillsControllerFindGroupedResponseSuccess = (skillsControllerFindGroupedResponse200) & {
  headers: Headers;
};
;

export type skillsControllerFindGroupedResponse = (skillsControllerFindGroupedResponseSuccess)

export const getSkillsControllerFindGroupedUrl = () => {


  

  return `/api/skills/grouped`
}

export const skillsControllerFindGrouped = async ( options?: RequestInit): Promise<skillsControllerFindGroupedResponse> => {
  
  const res = await fetch(getSkillsControllerFindGroupedUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: skillsControllerFindGroupedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as skillsControllerFindGroupedResponse
}


/**
 * @summary Get a skill by ID
 */
export type skillsControllerFindOneResponse200 = {
  data: SkillDto
  status: 200
}
    
export type skillsControllerFindOneResponseSuccess = (skillsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type skillsControllerFindOneResponse = (skillsControllerFindOneResponseSuccess)

export const getSkillsControllerFindOneUrl = (id: string,) => {


  

  return `/api/skills/${id}`
}

export const skillsControllerFindOne = async (id: string, options?: RequestInit): Promise<skillsControllerFindOneResponse> => {
  
  const res = await fetch(getSkillsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: skillsControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as skillsControllerFindOneResponse
}


/**
 * @summary Update a skill
 */
export type skillsControllerUpdateResponse200 = {
  data: SkillDto
  status: 200
}
    
export type skillsControllerUpdateResponseSuccess = (skillsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type skillsControllerUpdateResponse = (skillsControllerUpdateResponseSuccess)

export const getSkillsControllerUpdateUrl = (id: string,) => {


  

  return `/api/skills/${id}`
}

export const skillsControllerUpdate = async (id: string,
    updateSkillDto: UpdateSkillDto, options?: RequestInit): Promise<skillsControllerUpdateResponse> => {
  
  const res = await fetch(getSkillsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSkillDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: skillsControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as skillsControllerUpdateResponse
}


/**
 * @summary Delete a skill
 */
export type skillsControllerRemoveResponse200 = {
  data: SkillDto
  status: 200
}
    
export type skillsControllerRemoveResponseSuccess = (skillsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type skillsControllerRemoveResponse = (skillsControllerRemoveResponseSuccess)

export const getSkillsControllerRemoveUrl = (id: string,) => {


  

  return `/api/skills/${id}`
}

export const skillsControllerRemove = async (id: string, options?: RequestInit): Promise<skillsControllerRemoveResponse> => {
  
  const res = await fetch(getSkillsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: skillsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as skillsControllerRemoveResponse
}


