/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  CreateSkillDto,
  SkillDto,
  SkillsControllerFindAllParams,
  SkillsControllerFindGrouped200,
  UpdateSkillDto
} from '.././';


/**
 * @summary Create a new skill
 */
export const getSkillsControllerCreateUrl = () => {


  

  return `/api/skills`
}

export const skillsControllerCreate = async (createSkillDto: CreateSkillDto, options?: RequestInit): Promise<SkillDto> => {
  
  const res = await fetch(getSkillsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSkillDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: SkillDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary List all skills
 */
export const getSkillsControllerFindAllUrl = (params?: SkillsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/skills?${stringifiedParams}` : `/api/skills`
}

export const skillsControllerFindAll = async (params?: SkillsControllerFindAllParams, options?: RequestInit): Promise<SkillDto[]> => {
  
  const res = await fetch(getSkillsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: SkillDto[] = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Get skills grouped by category
 */
export const getSkillsControllerFindGroupedUrl = () => {


  

  return `/api/skills/grouped`
}

export const skillsControllerFindGrouped = async ( options?: RequestInit): Promise<SkillsControllerFindGrouped200> => {
  
  const res = await fetch(getSkillsControllerFindGroupedUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: SkillsControllerFindGrouped200 = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Get a skill by ID
 */
export const getSkillsControllerFindOneUrl = (id: string,) => {


  

  return `/api/skills/${id}`
}

export const skillsControllerFindOne = async (id: string, options?: RequestInit): Promise<SkillDto> => {
  
  const res = await fetch(getSkillsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: SkillDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Update a skill
 */
export const getSkillsControllerUpdateUrl = (id: string,) => {


  

  return `/api/skills/${id}`
}

export const skillsControllerUpdate = async (id: string,
    updateSkillDto: UpdateSkillDto, options?: RequestInit): Promise<SkillDto> => {
  
  const res = await fetch(getSkillsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSkillDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: SkillDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Delete a skill
 */
export const getSkillsControllerRemoveUrl = (id: string,) => {


  

  return `/api/skills/${id}`
}

export const skillsControllerRemove = async (id: string, options?: RequestInit): Promise<SkillDto> => {
  
  const res = await fetch(getSkillsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: SkillDto = body ? JSON.parse(body) : {}
  return data
}


