/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  CreateExperienceDto,
  ExperienceDto,
  UpdateExperienceDto
} from '.././';


/**
 * @summary Create a new experience entry
 */
export type experienceControllerCreateResponse201 = {
  data: ExperienceDto
  status: 201
}
    
export type experienceControllerCreateResponseSuccess = (experienceControllerCreateResponse201) & {
  headers: Headers;
};
;

export type experienceControllerCreateResponse = (experienceControllerCreateResponseSuccess)

export const getExperienceControllerCreateUrl = () => {


  

  return `/api/experience`
}

export const experienceControllerCreate = async (createExperienceDto: CreateExperienceDto, options?: RequestInit): Promise<experienceControllerCreateResponse> => {
  
  const res = await fetch(getExperienceControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createExperienceDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: experienceControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as experienceControllerCreateResponse
}


/**
 * @summary List all work experience
 */
export type experienceControllerFindAllResponse200 = {
  data: ExperienceDto[]
  status: 200
}
    
export type experienceControllerFindAllResponseSuccess = (experienceControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type experienceControllerFindAllResponse = (experienceControllerFindAllResponseSuccess)

export const getExperienceControllerFindAllUrl = () => {


  

  return `/api/experience`
}

export const experienceControllerFindAll = async ( options?: RequestInit): Promise<experienceControllerFindAllResponse> => {
  
  const res = await fetch(getExperienceControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: experienceControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as experienceControllerFindAllResponse
}


/**
 * @summary Get an experience entry by ID
 */
export type experienceControllerFindOneResponse200 = {
  data: ExperienceDto
  status: 200
}
    
export type experienceControllerFindOneResponseSuccess = (experienceControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type experienceControllerFindOneResponse = (experienceControllerFindOneResponseSuccess)

export const getExperienceControllerFindOneUrl = (id: string,) => {


  

  return `/api/experience/${id}`
}

export const experienceControllerFindOne = async (id: string, options?: RequestInit): Promise<experienceControllerFindOneResponse> => {
  
  const res = await fetch(getExperienceControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: experienceControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as experienceControllerFindOneResponse
}


/**
 * @summary Update an experience entry
 */
export type experienceControllerUpdateResponse200 = {
  data: ExperienceDto
  status: 200
}
    
export type experienceControllerUpdateResponseSuccess = (experienceControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type experienceControllerUpdateResponse = (experienceControllerUpdateResponseSuccess)

export const getExperienceControllerUpdateUrl = (id: string,) => {


  

  return `/api/experience/${id}`
}

export const experienceControllerUpdate = async (id: string,
    updateExperienceDto: UpdateExperienceDto, options?: RequestInit): Promise<experienceControllerUpdateResponse> => {
  
  const res = await fetch(getExperienceControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateExperienceDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: experienceControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as experienceControllerUpdateResponse
}


/**
 * @summary Delete an experience entry
 */
export type experienceControllerRemoveResponse200 = {
  data: ExperienceDto
  status: 200
}
    
export type experienceControllerRemoveResponseSuccess = (experienceControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type experienceControllerRemoveResponse = (experienceControllerRemoveResponseSuccess)

export const getExperienceControllerRemoveUrl = (id: string,) => {


  

  return `/api/experience/${id}`
}

export const experienceControllerRemove = async (id: string, options?: RequestInit): Promise<experienceControllerRemoveResponse> => {
  
  const res = await fetch(getExperienceControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: experienceControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as experienceControllerRemoveResponse
}


