/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  CreateExperienceDto,
  ExperienceDto,
  UpdateExperienceDto
} from '.././';


/**
 * @summary Create a new experience entry
 */
export const getExperienceControllerCreateUrl = () => {


  

  return `/api/experience`
}

export const experienceControllerCreate = async (createExperienceDto: CreateExperienceDto, options?: RequestInit): Promise<ExperienceDto> => {
  
  const res = await fetch(getExperienceControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createExperienceDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ExperienceDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary List all work experience
 */
export const getExperienceControllerFindAllUrl = () => {


  

  return `/api/experience`
}

export const experienceControllerFindAll = async ( options?: RequestInit): Promise<ExperienceDto[]> => {
  
  const res = await fetch(getExperienceControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ExperienceDto[] = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Get an experience entry by ID
 */
export const getExperienceControllerFindOneUrl = (id: string,) => {


  

  return `/api/experience/${id}`
}

export const experienceControllerFindOne = async (id: string, options?: RequestInit): Promise<ExperienceDto> => {
  
  const res = await fetch(getExperienceControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ExperienceDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Update an experience entry
 */
export const getExperienceControllerUpdateUrl = (id: string,) => {


  

  return `/api/experience/${id}`
}

export const experienceControllerUpdate = async (id: string,
    updateExperienceDto: UpdateExperienceDto, options?: RequestInit): Promise<ExperienceDto> => {
  
  const res = await fetch(getExperienceControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateExperienceDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ExperienceDto = body ? JSON.parse(body) : {}
  return data
}


/**
 * @summary Delete an experience entry
 */
export const getExperienceControllerRemoveUrl = (id: string,) => {


  

  return `/api/experience/${id}`
}

export const experienceControllerRemove = async (id: string, options?: RequestInit): Promise<ExperienceDto> => {
  
  const res = await fetch(getExperienceControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ExperienceDto = body ? JSON.parse(body) : {}
  return data
}


