/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';

export const appControllerGetHelloResponse = zod.string()


export const fileUploadControllerGetPresignedUrlBody = zod.object({

})


export const fileUploadControllerDeleteFileParams = zod.object({
  "key": zod.string(),
  "path": zod.string()
})


/**
 * @summary POST /api/users - Create a new user

Request body is automatically validated against CreateUserDto
If validation fails, NestJS returns 400 Bad Request
 */
export const usersControllerCreateBodyPasswordMin = 8;



export const usersControllerCreateBody = zod.object({
  "email": zod.email().describe('User\'s email address - used for login'),
  "password": zod.string().min(usersControllerCreateBodyPasswordMin).describe('User\'s password - will be hashed before storage'),
  "name": zod.string().optional().describe('User\'s display name (optional)'),
  "role": zod.enum(['ADMIN', 'VIEWER']).optional().describe('User\'s role - defaults to ADMIN in database if not provided')
})


/**
 * @summary GET /api/users - Get all users

Returns array of users (without passwords)
 */
export const usersControllerFindAllResponseItem = zod.object({

})
export const usersControllerFindAllResponse = zod.array(usersControllerFindAllResponseItem)


/**
 * @summary GET /api/users/:id - Get a single user by ID

@Param('id') extracts the :id from the URL
 */
export const usersControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const usersControllerFindOneResponse = zod.object({

})


/**
 * @summary PATCH /api/users/:id - Update a user

PATCH = partial update (only send fields you want to change)
PUT = full replacement (must send all fields)

We use PATCH because it's more practical for updates
 */
export const usersControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const usersControllerUpdateBodyPasswordMin = 8;



export const usersControllerUpdateBody = zod.object({
  "email": zod.email().optional().describe('User\'s email address - used for login'),
  "password": zod.string().min(usersControllerUpdateBodyPasswordMin).optional().describe('User\'s password - will be hashed before storage'),
  "name": zod.string().optional().describe('User\'s display name (optional)'),
  "role": zod.enum(['ADMIN', 'VIEWER']).optional().describe('User\'s role - defaults to ADMIN in database if not provided')
})

export const usersControllerUpdateResponse = zod.object({

})


/**
 * @summary DELETE /api/users/:id - Delete a user

Returns the deleted user data
 */
export const usersControllerRemoveParams = zod.object({
  "id": zod.string()
})

export const usersControllerRemoveResponse = zod.object({

})


/**
 * @summary Login with email and password
 */
export const authControllerLoginBodyPasswordMin = 8;



export const authControllerLoginBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(authControllerLoginBodyPasswordMin)
})

export const authControllerLoginResponse = zod.object({
  "access_token": zod.string().describe('JWT access token'),
  "user": zod.object({
  "id": zod.string().describe('User ID'),
  "email": zod.string().describe('User email'),
  "name": zod.string().nullable().describe('User name'),
  "role": zod.object({

}).describe('User role')
}).describe('Authenticated user')
})


/**
 * @summary Get current authenticated user profile
 */
export const authControllerGetMeResponse = zod.object({
  "id": zod.string().describe('User ID'),
  "email": zod.string().describe('User email'),
  "name": zod.string().nullable().describe('User name'),
  "role": zod.object({

}).describe('User role')
})


/**
 * @summary Create a new project
 */
export const projectsControllerCreateBodySlugMin = 2;


export const projectsControllerCreateBodySlugRegExp = new RegExp('^[a-z0-9-]+$');
export const projectsControllerCreateBodyTitleMin = 2;

export const projectsControllerCreateBodyDescriptionMin = 10;

export const projectsControllerCreateBodyOrderMin = 0;



export const projectsControllerCreateBody = zod.object({
  "slug": zod.string().min(projectsControllerCreateBodySlugMin).regex(projectsControllerCreateBodySlugRegExp).describe('URL-friendly identifier for the project'),
  "title": zod.string().min(projectsControllerCreateBodyTitleMin).describe('Display title'),
  "description": zod.string().min(projectsControllerCreateBodyDescriptionMin).optional().describe('Short description (for cards/listings)'),
  "longDescription": zod.string().optional().describe('Full description with details (optional)'),
  "status": zod.enum(['ACTIVE', 'COMPLETED', 'PAUSED', 'ARCHIVED']).describe('Project status'),
  "type": zod.enum(['PRODUCT', 'CLIENT', 'EXPERIMENT', 'LEARNING']).describe('Project type/category'),
  "url": zod.url().optional().describe('Live project URL (optional)'),
  "github": zod.string().optional().describe('GitHub repository URL (optional)aaa'),
  "featured": zod.boolean().optional().describe('Featured on homepage?'),
  "order": zod.number().min(projectsControllerCreateBodyOrderMin).optional().describe('Display order (lower = first)'),
  "startedAt": zod.string().optional().describe('When project was started'),
  "completedAt": zod.string().optional().describe('When project was completed (if applicable)'),
  "technologyIds": zod.array(zod.string()).optional().describe('Array of technology IDs to associate with this project'),
  "images": zod.array(zod.object({
  "url": zod.url(),
  "alt": zod.string().optional(),
  "order": zod.number()
})).optional().describe('Array of images for the project')
})


/**
 * @summary List all projects with optional filters
 */
export const projectsControllerFindAllQuerySkipMin = 0;

export const projectsControllerFindAllQueryTakeMax = 100;



export const projectsControllerFindAllQueryParams = zod.object({
  "status": zod.enum(['ACTIVE', 'COMPLETED', 'PAUSED', 'ARCHIVED']).optional().describe('Filter by project status'),
  "type": zod.enum(['PRODUCT', 'CLIENT', 'EXPERIMENT', 'LEARNING']).optional().describe('Filter by project type'),
  "featured": zod.enum(['true', 'false', '1', '0']).optional().describe('Filter featured projects only\n\nWORKAROUND: Query params come as strings. With enableImplicitConversion,\nthe string \"false\" becomes true (Boolean(\"false\") === true in JS).\nSolution: Keep as optional string, convert in the service layer.\n\nValid values: \"true\", \"false\", \"1\", \"0\"'),
  "skip": zod.number().min(projectsControllerFindAllQuerySkipMin).optional().describe('Number of records to skip (for pagination)'),
  "take": zod.number().min(1).max(projectsControllerFindAllQueryTakeMax).optional().describe('Number of records to return (limit)')
})

export const projectsControllerFindAllResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('Project ID'),
  "slug": zod.string().describe('URL-friendly slug'),
  "title": zod.string().describe('Display title'),
  "description": zod.string().nullable().describe('Short description'),
  "longDescription": zod.string().nullable().describe('Full description'),
  "status": zod.enum(['ACTIVE', 'COMPLETED', 'PAUSED', 'ARCHIVED']).describe('Project status'),
  "type": zod.enum(['PRODUCT', 'CLIENT', 'EXPERIMENT', 'LEARNING']).describe('Project type'),
  "url": zod.string().nullable().describe('Live project URL'),
  "github": zod.string().nullable().describe('GitHub repository URL'),
  "featured": zod.boolean().describe('Featured on homepage'),
  "order": zod.number().describe('Display order'),
  "startedAt": zod.iso.datetime({}).nullable().describe('When project was started'),
  "completedAt": zod.iso.datetime({}).nullable().describe('When project was completed'),
  "createdAt": zod.iso.datetime({}).describe('Creation timestamp'),
  "updatedAt": zod.iso.datetime({}).describe('Last update timestamp'),
  "technologies": zod.array(zod.object({
  "id": zod.string().describe('Technology ID'),
  "name": zod.string().describe('Technology name'),
  "icon": zod.string().nullable().describe('Icon identifier')
})).optional().describe('Associated technologies'),
  "images": zod.array(zod.object({
  "id": zod.string().optional(),
  "url": zod.url(),
  "alt": zod.string().optional(),
  "order": zod.number()
})).optional().describe('Project images')
})).describe('List of projects'),
  "meta": zod.object({
  "total": zod.number().describe('Total number of items'),
  "skip": zod.number().describe('Number of items skipped'),
  "take": zod.number().describe('Number of items per page'),
  "hasMore": zod.boolean().describe('Whether there are more items')
}).describe('Pagination metadata')
})


/**
 * @summary Get featured projects for homepage
 */
export const projectsControllerFindFeaturedResponseItem = zod.object({
  "id": zod.string().describe('Project ID'),
  "slug": zod.string().describe('URL-friendly slug'),
  "title": zod.string().describe('Display title'),
  "description": zod.string().nullable().describe('Short description'),
  "longDescription": zod.string().nullable().describe('Full description'),
  "status": zod.enum(['ACTIVE', 'COMPLETED', 'PAUSED', 'ARCHIVED']).describe('Project status'),
  "type": zod.enum(['PRODUCT', 'CLIENT', 'EXPERIMENT', 'LEARNING']).describe('Project type'),
  "url": zod.string().nullable().describe('Live project URL'),
  "github": zod.string().nullable().describe('GitHub repository URL'),
  "featured": zod.boolean().describe('Featured on homepage'),
  "order": zod.number().describe('Display order'),
  "startedAt": zod.iso.datetime({}).nullable().describe('When project was started'),
  "completedAt": zod.iso.datetime({}).nullable().describe('When project was completed'),
  "createdAt": zod.iso.datetime({}).describe('Creation timestamp'),
  "updatedAt": zod.iso.datetime({}).describe('Last update timestamp'),
  "technologies": zod.array(zod.object({
  "id": zod.string().describe('Technology ID'),
  "name": zod.string().describe('Technology name'),
  "icon": zod.string().nullable().describe('Icon identifier')
})).optional().describe('Associated technologies'),
  "images": zod.array(zod.object({
  "id": zod.string().optional(),
  "url": zod.url(),
  "alt": zod.string().optional(),
  "order": zod.number()
})).optional().describe('Project images')
})
export const projectsControllerFindFeaturedResponse = zod.array(projectsControllerFindFeaturedResponseItem)


/**
 * @summary Get a project by ID or slug
 */
export const projectsControllerFindOneParams = zod.object({
  "idOrSlug": zod.string()
})

export const projectsControllerFindOneResponse = zod.object({
  "id": zod.string().describe('Project ID'),
  "slug": zod.string().describe('URL-friendly slug'),
  "title": zod.string().describe('Display title'),
  "description": zod.string().nullable().describe('Short description'),
  "longDescription": zod.string().nullable().describe('Full description'),
  "status": zod.enum(['ACTIVE', 'COMPLETED', 'PAUSED', 'ARCHIVED']).describe('Project status'),
  "type": zod.enum(['PRODUCT', 'CLIENT', 'EXPERIMENT', 'LEARNING']).describe('Project type'),
  "url": zod.string().nullable().describe('Live project URL'),
  "github": zod.string().nullable().describe('GitHub repository URL'),
  "featured": zod.boolean().describe('Featured on homepage'),
  "order": zod.number().describe('Display order'),
  "startedAt": zod.iso.datetime({}).nullable().describe('When project was started'),
  "completedAt": zod.iso.datetime({}).nullable().describe('When project was completed'),
  "createdAt": zod.iso.datetime({}).describe('Creation timestamp'),
  "updatedAt": zod.iso.datetime({}).describe('Last update timestamp'),
  "technologies": zod.array(zod.object({
  "id": zod.string().describe('Technology ID'),
  "name": zod.string().describe('Technology name'),
  "icon": zod.string().nullable().describe('Icon identifier')
})).optional().describe('Associated technologies'),
  "images": zod.array(zod.object({
  "id": zod.string().optional(),
  "url": zod.url(),
  "alt": zod.string().optional(),
  "order": zod.number()
})).optional().describe('Project images')
})


/**
 * @summary Update a project
 */
export const projectsControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const projectsControllerUpdateBodySlugMin = 2;


export const projectsControllerUpdateBodySlugRegExp = new RegExp('^[a-z0-9-]+$');
export const projectsControllerUpdateBodyTitleMin = 2;

export const projectsControllerUpdateBodyDescriptionMin = 10;

export const projectsControllerUpdateBodyOrderMin = 0;



export const projectsControllerUpdateBody = zod.object({
  "images": zod.array(zod.object({
  "id": zod.string().optional(),
  "url": zod.url(),
  "alt": zod.string().optional(),
  "order": zod.number()
})).optional().describe('Array of images for the project\nThis will replace all existing images with the new set'),
  "slug": zod.string().min(projectsControllerUpdateBodySlugMin).regex(projectsControllerUpdateBodySlugRegExp).optional().describe('URL-friendly identifier for the project'),
  "title": zod.string().min(projectsControllerUpdateBodyTitleMin).optional().describe('Display title'),
  "description": zod.string().min(projectsControllerUpdateBodyDescriptionMin).optional().describe('Short description (for cards/listings)'),
  "longDescription": zod.string().optional().describe('Full description with details (optional)'),
  "status": zod.enum(['ACTIVE', 'COMPLETED', 'PAUSED', 'ARCHIVED']).optional().describe('Project status'),
  "type": zod.enum(['PRODUCT', 'CLIENT', 'EXPERIMENT', 'LEARNING']).optional().describe('Project type/category'),
  "url": zod.url().optional().describe('Live project URL (optional)'),
  "github": zod.string().optional().describe('GitHub repository URL (optional)aaa'),
  "featured": zod.boolean().optional().describe('Featured on homepage?'),
  "order": zod.number().min(projectsControllerUpdateBodyOrderMin).optional().describe('Display order (lower = first)'),
  "startedAt": zod.string().optional().describe('When project was started'),
  "completedAt": zod.string().optional().describe('When project was completed (if applicable)'),
  "technologyIds": zod.array(zod.string()).optional().describe('Array of technology IDs to associate with this project')
})

export const projectsControllerUpdateResponse = zod.object({
  "id": zod.string().describe('Project ID'),
  "slug": zod.string().describe('URL-friendly slug'),
  "title": zod.string().describe('Display title'),
  "description": zod.string().nullable().describe('Short description'),
  "longDescription": zod.string().nullable().describe('Full description'),
  "status": zod.enum(['ACTIVE', 'COMPLETED', 'PAUSED', 'ARCHIVED']).describe('Project status'),
  "type": zod.enum(['PRODUCT', 'CLIENT', 'EXPERIMENT', 'LEARNING']).describe('Project type'),
  "url": zod.string().nullable().describe('Live project URL'),
  "github": zod.string().nullable().describe('GitHub repository URL'),
  "featured": zod.boolean().describe('Featured on homepage'),
  "order": zod.number().describe('Display order'),
  "startedAt": zod.iso.datetime({}).nullable().describe('When project was started'),
  "completedAt": zod.iso.datetime({}).nullable().describe('When project was completed'),
  "createdAt": zod.iso.datetime({}).describe('Creation timestamp'),
  "updatedAt": zod.iso.datetime({}).describe('Last update timestamp'),
  "technologies": zod.array(zod.object({
  "id": zod.string().describe('Technology ID'),
  "name": zod.string().describe('Technology name'),
  "icon": zod.string().nullable().describe('Icon identifier')
})).optional().describe('Associated technologies'),
  "images": zod.array(zod.object({
  "id": zod.string().optional(),
  "url": zod.url(),
  "alt": zod.string().optional(),
  "order": zod.number()
})).optional().describe('Project images')
})


/**
 * @summary Delete a project
 */
export const projectsControllerRemoveParams = zod.object({
  "id": zod.string()
})

export const projectsControllerRemoveResponse = zod.object({
  "id": zod.string().describe('Project ID'),
  "slug": zod.string().describe('URL-friendly slug'),
  "title": zod.string().describe('Display title'),
  "description": zod.string().nullable().describe('Short description'),
  "longDescription": zod.string().nullable().describe('Full description'),
  "status": zod.enum(['ACTIVE', 'COMPLETED', 'PAUSED', 'ARCHIVED']).describe('Project status'),
  "type": zod.enum(['PRODUCT', 'CLIENT', 'EXPERIMENT', 'LEARNING']).describe('Project type'),
  "url": zod.string().nullable().describe('Live project URL'),
  "github": zod.string().nullable().describe('GitHub repository URL'),
  "featured": zod.boolean().describe('Featured on homepage'),
  "order": zod.number().describe('Display order'),
  "startedAt": zod.iso.datetime({}).nullable().describe('When project was started'),
  "completedAt": zod.iso.datetime({}).nullable().describe('When project was completed'),
  "createdAt": zod.iso.datetime({}).describe('Creation timestamp'),
  "updatedAt": zod.iso.datetime({}).describe('Last update timestamp'),
  "technologies": zod.array(zod.object({
  "id": zod.string().describe('Technology ID'),
  "name": zod.string().describe('Technology name'),
  "icon": zod.string().nullable().describe('Icon identifier')
})).optional().describe('Associated technologies'),
  "images": zod.array(zod.object({
  "id": zod.string().optional(),
  "url": zod.url(),
  "alt": zod.string().optional(),
  "order": zod.number()
})).optional().describe('Project images')
})


/**
 * @summary Create a new technology
 */



export const technologiesControllerCreateBody = zod.object({
  "name": zod.string().min(1).describe('Technology name (unique)'),
  "icon": zod.string().optional().describe('Icon identifier or URL (optional)\nCould be a simple icon name or full URL')
})


/**
 * @summary List all technologies
 */
export const technologiesControllerFindAllQueryParams = zod.object({
  "skip": zod.string(),
  "take": zod.string()
})

export const technologiesControllerFindAllResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('Technology ID'),
  "name": zod.string().describe('Technology name'),
  "icon": zod.string().nullable().describe('Icon identifier')
})).describe('List of technologies'),
  "meta": zod.object({
  "total": zod.number().describe('Total number of items'),
  "skip": zod.number().describe('Number of items skipped'),
  "take": zod.number().describe('Number of items per page'),
  "hasMore": zod.boolean().describe('Whether there are more items')
}).describe('Pagination metadata')
})


/**
 * @summary Get a technology by ID
 */
export const technologiesControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const technologiesControllerFindOneResponse = zod.object({
  "id": zod.string().describe('Technology ID'),
  "name": zod.string().describe('Technology name'),
  "icon": zod.string().nullable().describe('Icon identifier')
})


/**
 * @summary Update a technology
 */
export const technologiesControllerUpdateParams = zod.object({
  "id": zod.string()
})




export const technologiesControllerUpdateBody = zod.object({
  "name": zod.string().min(1).optional().describe('Technology name (unique)'),
  "icon": zod.string().optional().describe('Icon identifier or URL (optional)\nCould be a simple icon name or full URL')
})

export const technologiesControllerUpdateResponse = zod.object({
  "id": zod.string().describe('Technology ID'),
  "name": zod.string().describe('Technology name'),
  "icon": zod.string().nullable().describe('Icon identifier')
})


/**
 * @summary Delete a technology
 */
export const technologiesControllerRemoveParams = zod.object({
  "id": zod.string()
})

export const technologiesControllerRemoveResponse = zod.object({
  "id": zod.string().describe('Technology ID'),
  "name": zod.string().describe('Technology name'),
  "icon": zod.string().nullable().describe('Icon identifier')
})


/**
 * @summary Create a new skill
 */

export const skillsControllerCreateBodyLevelDefault = 80;
export const skillsControllerCreateBodyLevelMin = 0;
export const skillsControllerCreateBodyLevelMax = 100;

export const skillsControllerCreateBodyOrderDefault = 0;
export const skillsControllerCreateBodyOrderMin = 0;



export const skillsControllerCreateBody = zod.object({
  "name": zod.string().min(1).describe('Skill name'),
  "category": zod.enum(['FRONTEND', 'BACKEND', 'DATABASE', 'DEVOPS', 'TOOLS', 'AI']).describe('Skill category for grouping'),
  "level": zod.number().min(skillsControllerCreateBodyLevelMin).max(skillsControllerCreateBodyLevelMax).default(skillsControllerCreateBodyLevelDefault).describe('Proficiency level (0-100)'),
  "order": zod.number().min(skillsControllerCreateBodyOrderMin).optional().describe('Display order (lower = first)')
})


/**
 * @summary List all skills
 */
export const skillsControllerFindAllQueryParams = zod.object({
  "category": zod.enum(['FRONTEND', 'BACKEND', 'DATABASE', 'DEVOPS', 'TOOLS', 'AI']).optional()
})

export const skillsControllerFindAllResponseItem = zod.object({
  "id": zod.string().describe('Skill ID'),
  "name": zod.string().describe('Skill name'),
  "category": zod.string().describe('Skill category for grouping'),
  "level": zod.number().describe('Proficiency level (0-100)'),
  "order": zod.number().describe('Display order (lower = first)')
})
export const skillsControllerFindAllResponse = zod.array(skillsControllerFindAllResponseItem)


/**
 * @summary Get skills grouped by category
 */
export const skillsControllerFindGroupedResponse = zod.object({

})


/**
 * @summary Get a skill by ID
 */
export const skillsControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const skillsControllerFindOneResponse = zod.object({
  "id": zod.string().describe('Skill ID'),
  "name": zod.string().describe('Skill name'),
  "category": zod.string().describe('Skill category for grouping'),
  "level": zod.number().describe('Proficiency level (0-100)'),
  "order": zod.number().describe('Display order (lower = first)')
})


/**
 * @summary Update a skill
 */
export const skillsControllerUpdateParams = zod.object({
  "id": zod.string()
})


export const skillsControllerUpdateBodyLevelDefault = 80;
export const skillsControllerUpdateBodyLevelMin = 0;
export const skillsControllerUpdateBodyLevelMax = 100;

export const skillsControllerUpdateBodyOrderDefault = 0;
export const skillsControllerUpdateBodyOrderMin = 0;



export const skillsControllerUpdateBody = zod.object({
  "name": zod.string().min(1).optional().describe('Skill name'),
  "category": zod.enum(['FRONTEND', 'BACKEND', 'DATABASE', 'DEVOPS', 'TOOLS', 'AI']).optional().describe('Skill category for grouping'),
  "level": zod.number().min(skillsControllerUpdateBodyLevelMin).max(skillsControllerUpdateBodyLevelMax).default(skillsControllerUpdateBodyLevelDefault).describe('Proficiency level (0-100)'),
  "order": zod.number().min(skillsControllerUpdateBodyOrderMin).optional().describe('Display order (lower = first)')
})

export const skillsControllerUpdateResponse = zod.object({
  "id": zod.string().describe('Skill ID'),
  "name": zod.string().describe('Skill name'),
  "category": zod.string().describe('Skill category for grouping'),
  "level": zod.number().describe('Proficiency level (0-100)'),
  "order": zod.number().describe('Display order (lower = first)')
})


/**
 * @summary Delete a skill
 */
export const skillsControllerRemoveParams = zod.object({
  "id": zod.string()
})

export const skillsControllerRemoveResponse = zod.object({
  "id": zod.string().describe('Skill ID'),
  "name": zod.string().describe('Skill name'),
  "category": zod.string().describe('Skill category for grouping'),
  "level": zod.number().describe('Proficiency level (0-100)'),
  "order": zod.number().describe('Display order (lower = first)')
})


/**
 * @summary Create a new experience entry
 */


export const experienceControllerCreateBodyCurrentDefault = false;export const experienceControllerCreateBodyOrderDefault = 0;
export const experienceControllerCreateBodyOrderMin = 0;



export const experienceControllerCreateBody = zod.object({
  "company": zod.string().min(1).describe('Company name'),
  "role": zod.string().min(1).describe('Job role/title'),
  "description": zod.string().optional().describe('Role description (optional, can include achievements)'),
  "startDate": zod.string().describe('Start date'),
  "endDate": zod.string().optional().describe('End date (null if current position)'),
  "current": zod.boolean().optional().describe('Is this the current position?'),
  "order": zod.number().min(experienceControllerCreateBodyOrderMin).optional().describe('Display order (lower = first, typically most recent)')
})


/**
 * @summary List all work experience
 */
export const experienceControllerFindAllResponseItem = zod.object({
  "id": zod.string().describe('Experience ID'),
  "company": zod.string().describe('Company name'),
  "role": zod.string().describe('Job role/title'),
  "description": zod.string().nullable().describe('Role description'),
  "startDate": zod.iso.datetime({}).describe('Start date'),
  "endDate": zod.iso.datetime({}).nullable().describe('End date (null if current position)'),
  "current": zod.boolean().describe('Is this the current position?'),
  "order": zod.number().describe('Display order (lower = first)')
})
export const experienceControllerFindAllResponse = zod.array(experienceControllerFindAllResponseItem)


/**
 * @summary Get an experience entry by ID
 */
export const experienceControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const experienceControllerFindOneResponse = zod.object({
  "id": zod.string().describe('Experience ID'),
  "company": zod.string().describe('Company name'),
  "role": zod.string().describe('Job role/title'),
  "description": zod.string().nullable().describe('Role description'),
  "startDate": zod.iso.datetime({}).describe('Start date'),
  "endDate": zod.iso.datetime({}).nullable().describe('End date (null if current position)'),
  "current": zod.boolean().describe('Is this the current position?'),
  "order": zod.number().describe('Display order (lower = first)')
})


/**
 * @summary Update an experience entry
 */
export const experienceControllerUpdateParams = zod.object({
  "id": zod.string()
})



export const experienceControllerUpdateBodyCurrentDefault = false;export const experienceControllerUpdateBodyOrderDefault = 0;
export const experienceControllerUpdateBodyOrderMin = 0;



export const experienceControllerUpdateBody = zod.object({
  "company": zod.string().min(1).optional().describe('Company name'),
  "role": zod.string().min(1).optional().describe('Job role/title'),
  "description": zod.string().optional().describe('Role description (optional, can include achievements)'),
  "startDate": zod.string().optional().describe('Start date'),
  "endDate": zod.string().optional().describe('End date (null if current position)'),
  "current": zod.boolean().optional().describe('Is this the current position?'),
  "order": zod.number().min(experienceControllerUpdateBodyOrderMin).optional().describe('Display order (lower = first, typically most recent)')
})

export const experienceControllerUpdateResponse = zod.object({
  "id": zod.string().describe('Experience ID'),
  "company": zod.string().describe('Company name'),
  "role": zod.string().describe('Job role/title'),
  "description": zod.string().nullable().describe('Role description'),
  "startDate": zod.iso.datetime({}).describe('Start date'),
  "endDate": zod.iso.datetime({}).nullable().describe('End date (null if current position)'),
  "current": zod.boolean().describe('Is this the current position?'),
  "order": zod.number().describe('Display order (lower = first)')
})


/**
 * @summary Delete an experience entry
 */
export const experienceControllerRemoveParams = zod.object({
  "id": zod.string()
})

export const experienceControllerRemoveResponse = zod.object({
  "id": zod.string().describe('Experience ID'),
  "company": zod.string().describe('Company name'),
  "role": zod.string().describe('Job role/title'),
  "description": zod.string().nullable().describe('Role description'),
  "startDate": zod.iso.datetime({}).describe('Start date'),
  "endDate": zod.iso.datetime({}).nullable().describe('End date (null if current position)'),
  "current": zod.boolean().describe('Is this the current position?'),
  "order": zod.number().describe('Display order (lower = first)')
})


/**
 * @summary Upload an image file
 */
export const mediaControllerUploadFileBody = zod.object({
  "file": zod.instanceof(File).optional()
})


/**
 * @summary Delete an uploaded file
 */
export const mediaControllerDeleteFileParams = zod.object({
  "key": zod.string()
})
