/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * ayyaz.dev API
 * 
      Portfolio API for ayyaz.dev

      ## Authentication
      Most endpoints are public. Protected endpoints require a JWT token.

      ## Getting Started
      1. Create a user via POST /api/users
      2. Login via POST /api/auth/login to get a token
      3. Use the token in the Authorize button above
    
 * OpenAPI spec version: 1.0
 */
import type {
  PresignedUrlRequestDto
} from '.././';


export const getFileUploadControllerGetPresignedUrlUrl = () => {


  

  return `/api/upload/presigned-url`
}

export const fileUploadControllerGetPresignedUrl = async (presignedUrlRequestDto: PresignedUrlRequestDto, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getFileUploadControllerGetPresignedUrlUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      presignedUrlRequestDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}


export const getFileUploadControllerDeleteFileUrl = (key: string,
    path: string,) => {


  

  return `/api/upload/${key}/${path}`
}

export const fileUploadControllerDeleteFile = async (key: string,
    path: string, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getFileUploadControllerDeleteFileUrl(key,path),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}


export const getFileUploadControllerGetConfigUrl = () => {


  

  return `/api/upload/config`
}

export const fileUploadControllerGetConfig = async ( options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getFileUploadControllerGetConfigUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}


